easy_admin:
    entities:
        User:
            class: App\Entity\User
            list:
                fields:
                    - id
                    - email
                    - roles
                actions:
                    - { name: 'edit', label: 'Edit' }
                    - { name: 'delete', label: 'Delete' }