twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['bootstrap_5_layout.html.twig']

framework:
    # error_controller: App\Controller\ErrorController::showException
    
when@test:
    twig:
        strict_variables: true
        
