vich_uploader:
    db_driver: orm

    mappings:
       recipe_images:
        uri_prefix: /images
        upload_destination: '%kernel.project_dir%/public/uploads/images'
        namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
